homepage:
    path:   /
    defaults:  { _controller: AppBundle:Login:login }
login:
    path:     /login
    defaults: { _controller: AppBundle:Login:login }
logout:
        path:     /logout
        defaults: { _controller: AppBundle:Login:logout }
new_budget:
    path:     /new_budget
    defaults: { _controller: AppBundle:Budget:newBudget }
new_initiative:
    path:     /new_initiative
    defaults: { _controller: AppBundle:Initiative:newInitiative }