<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container16risno\appTestDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container16risno/appTestDebugProjectContainer.php') {
    touch(__DIR__.'/Container16risno.legacy');

    return;
}

if (!\class_exists(appTestDebugProjectContainer::class, false)) {
    \class_alias(\Container16risno\appTestDebugProjectContainer::class, appTestDebugProjectContainer::class, false);
}

return new \Container16risno\appTestDebugProjectContainer(array(
    'container.build_hash' => '16risno',
    'container.build_id' => '31f6889d',
    'container.build_time' => 1519949526,
));
