<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVm9jwxx\appTestDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVm9jwxx/appTestDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerVm9jwxx.legacy');

    return;
}

if (!\class_exists(appTestDebugProjectContainer::class, false)) {
    \class_alias(\ContainerVm9jwxx\appTestDebugProjectContainer::class, appTestDebugProjectContainer::class, false);
}

return new \ContainerVm9jwxx\appTestDebugProjectContainer(array(
    'container.build_hash' => 'Vm9jwxx',
    'container.build_id' => 'd7866799',
    'container.build_time' => 1519903469,
));
