<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXopjqmo\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXopjqmo/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXopjqmo.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXopjqmo\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerXopjqmo\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Xopjqmo',
    'container.build_id' => 'f9766202',
    'container.build_time' => 1519908323,
));
