<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRmrhvcq\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRmrhvcq/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerRmrhvcq.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerRmrhvcq\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerRmrhvcq\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Rmrhvcq',
    'container.build_id' => 'f29e31a8',
    'container.build_time' => 1519934530,
));
