<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPmgbwvk\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPmgbwvk/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerPmgbwvk.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerPmgbwvk\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerPmgbwvk\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Pmgbwvk',
    'container.build_id' => '6b747f48',
    'container.build_time' => 1519950654,
));
